// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs9KmP2kokILzLuyC1lSdofF-st2M_J18',
    appId: '1:168512024611:web:4f3773d0a55b1aef0d0196',
    messagingSenderId: '168512024611',
    projectId: 'progressaapp-489e9',
    authDomain: 'progressaapp-489e9.firebaseapp.com',
    storageBucket: 'progressaapp-489e9.firebasestorage.app',
    measurementId: 'G-Y7ZTDSJJKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxv663LiWJJt6Uy1yKODgz7VqQCJVVj6Y',
    appId: '1:168512024611:android:02a729140644229d0d0196',
    messagingSenderId: '168512024611',
    projectId: 'progressaapp-489e9',
    storageBucket: 'progressaapp-489e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHR4uVQVcxGfeCCuX-q9qjH7N_d7tWdT4',
    appId: '1:168512024611:ios:fe4bb34f586f16c40d0196',
    messagingSenderId: '168512024611',
    projectId: 'progressaapp-489e9',
    storageBucket: 'progressaapp-489e9.firebasestorage.app',
    iosBundleId: 'dev.dvcanache.notegym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHR4uVQVcxGfeCCuX-q9qjH7N_d7tWdT4',
    appId: '1:168512024611:ios:fe4bb34f586f16c40d0196',
    messagingSenderId: '168512024611',
    projectId: 'progressaapp-489e9',
    storageBucket: 'progressaapp-489e9.firebasestorage.app',
    iosBundleId: 'dev.dvcanache.notegym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs9KmP2kokILzLuyC1lSdofF-st2M_J18',
    appId: '1:168512024611:web:9dc8318bb7db5c840d0196',
    messagingSenderId: '168512024611',
    projectId: 'progressaapp-489e9',
    authDomain: 'progressaapp-489e9.firebaseapp.com',
    storageBucket: 'progressaapp-489e9.firebasestorage.app',
    measurementId: 'G-84F7WQWSWM',
  );
}
